<?php get_header(); ?>
<main>
<section class="hero">
  <div class="hero-media" role="img" aria-label="Italienisches Gelato in einer Eiswaffel"></div><div class="hero-overlay"></div>
  <div class="hero-content container">
    <div class="hero-kicker reveal">Neubiberg · Seit vielen Jahren ein Treffpunkt</div>
    <h1 class="reveal">Ein kleines Stück<br><em>Italia</em> vor der Tür.</h1>
    <p class="hero-lead reveal">Cremiges Gelato, knusprige Steinofenpizza und italienische Küche – unkompliziert, herzlich und mitten in Neubiberg.</p>
    <div class="hero-actions reveal"><a class="btn btn-light" href="<?php echo esc_url(delfino_menu_url()); ?>">Speisekarte entdecken</a><a class="btn btn-glass" href="#besuch">Vorbeikommen</a></div>
  </div>
  <a class="scroll-cue" href="#intro" aria-label="Weiter nach unten"><span>Entdecken</span><i></i></a>
</section>
<section class="intro section" id="intro"><div class="container intro-grid"><div class="eyebrow reveal">La dolce vita in Neubiberg</div><div><h2 class="section-title reveal">Gelato. Pizza. Pasta.<br><span>Und Zeit zum Genießen.</span></h2><p class="big-copy reveal">Delfino verbindet die Leichtigkeit einer italienischen Gelateria mit ehrlicher Küche. Ob eine schnelle Kugel Eis, Cappuccino in der Sonne oder Pizza am Abend – hier darf der Alltag kurz Pause machen.</p></div></div></section>
<section class="showcase section" id="genuss"><div class="container"><div class="section-head reveal"><div><p class="eyebrow">Unsere Klassiker</p><h2 class="section-title compact">Drei Gründe,<br>länger zu bleiben.</h2></div><a class="arrow-link" href="<?php echo esc_url(delfino_menu_url()); ?>">Zur Speisekarte <span>↗</span></a></div>
<div class="feature-grid">
<a class="feature-card feature-card-large reveal feature-card-link" href="<?php echo esc_url(delfino_menu_url().'#cat-eis'); ?>"><div class="feature-image gelato-img"></div><div class="feature-content"><span class="feature-number">01</span><div><h3>Gelato</h3><p>Von fruchtig bis cremig – Klassiker und Lieblingssorten für große und kleine Eispausen.</p></div></div></a>
<a class="feature-card reveal feature-card-link" href="<?php echo esc_url(delfino_menu_url().'#cat-pizza'); ?>"><div class="feature-image pizza-img"></div><div class="feature-content"><span class="feature-number">02</span><div><h3>Steinofenpizza</h3><p>Knuspriger Rand, kräftige Tomate, geschmolzener Käse. Einfach so, wie Pizza sein soll.</p></div></div></a>
<a class="feature-card reveal feature-card-link" href="<?php echo esc_url(delfino_menu_url().'#cat-pasta'); ?>"><div class="feature-image pasta-img"></div><div class="feature-content"><span class="feature-number">03</span><div><h3>Pasta & mehr</h3><p>Italienische Lieblingsgerichte, Antipasti und Panini – frisch, unkompliziert und voller Geschmack.</p></div></div></a>
</div></div></section>
<section class="menu-preview section"><div class="container menu-preview-grid"><div class="menu-copy reveal"><p class="eyebrow">Ein Blick in die Karte</p><h2 class="section-title compact">Was darf es heute sein?</h2><p>Die Speisekarte wird direkt aus WooCommerce gespeist. Preise und Produkte bleiben so automatisch aktuell.</p><a class="btn btn-dark" href="<?php echo esc_url(delfino_menu_url()); ?>">Komplette Speisekarte</a></div><div class="menu-list reveal"><div class="menu-row"><div><strong>Pizza</strong><small>Knusprig aus dem Ofen</small></div><span>entdecken</span></div><div class="menu-row"><div><strong>Pasta</strong><small>Italienische Klassiker</small></div><span>entdecken</span></div><div class="menu-row"><div><strong>Antipasti & Salate</strong><small>Zum Teilen oder allein genießen</small></div><span>entdecken</span></div><div class="menu-row"><div><strong>Gelato</strong><small>Viele Sorten zur Auswahl</small></div><span>entdecken</span></div></div></div></section>
<section class="split-story section" id="feiern"><div class="split-story-media reveal" role="img" aria-label="Eiscafé Delfino in Neubiberg"></div><div class="split-story-copy"><div class="story-inner reveal"><p class="eyebrow light">Mehr als nur ein Café</p><h2>Feiern, zusammensitzen, genießen.</h2><p>Ob Geburtstag, Familienrunde oder ein besonderer Anlass: Im Delfino könnt ihr auch gemeinsam vor Ort feiern. Für Möglichkeiten und Reservierungen einfach kurz anrufen.</p><a class="btn btn-light" href="tel:+4989604061">Jetzt anrufen</a></div></div></section>
<section class="visit section" id="besuch"><div class="container visit-grid"><div class="visit-image reveal" role="img" aria-label="Innenraum des Eiscafé Delfino"></div><div class="visit-card reveal"><p class="eyebrow">Komm vorbei</p><h2 class="section-title compact">Dein Platz<br>in Neubiberg.</h2><div class="visit-info"><div><span>Adresse</span><strong>Hauptstraße 55<br>85579 Neubiberg</strong></div><div><span>Telefon</span><a href="tel:+4989604061">089 604061</a></div></div><div class="visit-actions"><a class="btn btn-dark" href="https://www.google.com/maps/search/?api=1&query=Eiscaf%C3%A9+Delfino+Hauptstra%C3%9Fe+55+85579+Neubiberg" target="_blank" rel="noopener">Route öffnen</a><a class="arrow-link" href="https://www.instagram.com/eiscafedelfino/" target="_blank" rel="noopener">Instagram <span>↗</span></a></div></div></div></section>
<section class="cta-band"><div class="container cta-band-inner reveal"><div><p class="eyebrow light">Heute Lust auf Italien?</p><h2>Hier auswählen.<br>Direkt bestellen.</h2></div><a class="btn btn-light btn-xl" href="<?php echo esc_url(delfino_order_url()); ?>">Online bestellen <span>↗</span></a></div></section>
</main>
<?php get_footer(); ?>
